/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./src/components/article/ArticleItem.vue')['default']
    CaseTable: typeof import('./src/components/table/CaseTable.vue')['default']
    CommentDisplay: typeof import('./src/components/comment/CommentDisplay.vue')['default']
    CommentItem: typeof import('./src/components/comment/CommentItem.vue')['default']
    ConfirmBox: typeof import('./src/components/dialogs/ConfirmBox.vue')['default']
    CookieInput: typeof import('./src/components/input/CookieInput.vue')['default']
    CookieNav: typeof import('./src/components/nav/CookieNav.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmailInput: typeof import('./src/components/input/EmailInput.vue')['default']
    EmptyItem: typeof import('./src/components/empty/EmptyItem.vue')['default']
    IssueCase: typeof import('./src/components/issue/IssueCase.vue')['default']
    IssueItem: typeof import('./src/components/issue/IssueItem.vue')['default']
    ListItem: typeof import('./src/components/list/ListItem.vue')['default']
    LoaderItem: typeof import('./src/components/common/LoaderItem.vue')['default']
    LogoItem: typeof import('./src/components/common/LogoItem.vue')['default']
    PaginationItem: typeof import('./src/components/pagination/PaginationItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SevenButton: typeof import('./src/components/common/SevenButton.vue')['default']
    SevenSearch: typeof import('./src/components/common/SevenSearch.vue')['default']
    TabsNav: typeof import('./src/components/nav/TabsNav.vue')['default']
    UploadItem: typeof import('./src/components/UploadItem.vue')['default']
  }
}
